apiVersion: apps/v1
kind: Deployment
metadata:
  name: ce-smart-career-frontend-prd
  namespace: ce-smart-career
spec:
  replicas: 4
  selector:
    matchLabels:
      app: ce-smart-career-frontend-prd
  template:
    metadata:
      labels:
        app: ce-smart-career-frontend-prd
      annotations:
        redeployTimestamp: "{{ timestamp }}"
    spec:
      containers:
        - name: ce-smart-career-frontend-prd
          image: ghcr.io/ce-next-gen/ce-smart-career-2024-prd:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
      imagePullSecrets:
        - name: registry