apiVersion: apps/v1
kind: Deployment
metadata:
  name: ce-smart-career-frontend-prd
  namespace: ce-smart-career
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ce-smart-career-frontend-prd
  template:
    metadata:
      labels:
        app: ce-smart-career-frontend-prd
      annotations:
        redeployTimestamp: "{{ timestamp }}"
    spec:
      containers:
        - name: ce-smart-career-frontend-prd
          image: ghcr.io/ce-smart-career/ce-smart-career-2024-prd:latest
          imagePullPolicy: Always
          env:
            - name: NOCODB_API_URL
              value: "https://api.career.ktyhon.online/api/v2/tables"
            - name: NOCODB_API_TOKEN
              value: "gfu57tftfdyertdxhfdteto"
          ports:
            - containerPort: 3000
      imagePullSecrets:
        - name: registry