import type { Metadata } from 'next';
import { IBM_Plex_Sans_Thai } from 'next/font/google';
import '@/shared/style/globals.css';
import { cn } from '@/shared/utils';

const ibmPlexSansThai = IBM_Plex_Sans_Thai({
  subsets: ['thai'],
  weight: ['400', '500', '600', '700'],
  display: 'swap',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn('antialiased', ibmPlexSansThai.className, 'w-screen')}
      >
        {children}
      </body>
    </html>
  );
}
