name: CI

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - develop

jobs:
  lint-and-build:
    name: lint-and-build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js Environment
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Setup pnpm
        uses: pnpm/action-setup@v4.0.0
        with:
          version: 9
          
      - name: Create .env file
        run: |
          echo "NOCODB_API_TOKEN=${{ secrets.NOCODB_API_TOKEN }}" >> .env
          echo "NOCODB_API_URL=${{ secrets.NOCODB_API_URL }}" >> .env

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: Run linting
        run: pnpm lint-staged --allow-empty

      - name: Build application
        run: pnpm run build