name: CI/CD
on:
  push:
    branches:
      - develop

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ secrets.USER }}
          password: ${{ secrets.GTK }}

      - name: Build and push the Docker image
        uses: docker/build-push-action@v3
        with:
          build-args: |
            NEXT_PUBLIC_API_URL=${{secrets.NEXT_PUBLIC_API_URL_PRD}}
          push: true
          tags: |
            ghcr.io/ce-next-gen/${{ github.event.repository.name }}-prd:latest
      
  deploy:
    name: Deploy
    needs: build
    runs-on: label-1
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Deploy to our k8s
        run: |
          microk8s kubectl apply -f deploy/deployment.yml
          microk8s kubectl rollout restart deployment/ce-next-gen-2024-frontend-prd -n ce-next-gen-prd
          microk8s kubectl apply -f deploy/service.yml
          microk8s kubectl apply -f deploy/ingress.yml