name: CI/CD
on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ secrets.USER }}
          password: ${{ secrets.GTK }}

      - name: Build and push the Docker image
        uses: docker/build-push-action@v3
        with:
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: |
            ghcr.io/ce-next-gen/${{ github.event.repository.name }}-prd:latest
          secrets: |
            NOCODB_API_TOKEN=${{ secrets.NOCODB_API_TOKEN }}
            NOCODB_API_URL=${{ secrets.NOCODB_API_URL }}

  deploy:
    name: Deploy
    needs: build
    runs-on: label-1
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Deploy to our k8s
        run: |
          microk8s kubectl apply -f deploy/deployment.yml
          microk8s kubectl rollout restart deployment/ce-smart-career-frontend-prd -n ce-smart-career
          microk8s kubectl apply -f deploy/service.yml
          microk8s kubectl apply -f deploy/ingress.yml
